services:
    nginx:
        image: nginx
        ports:
            - 8080:80
        volumes:
            - ./build/scripts:/usr/share/nginx/html/scripts
            - ./src:/usr/share/nginx/html
    node:
        image: node
        volumes:
            - ./package.json:/usr/app/package.json
            - ./tsconfig.json:/usr/app/tsconfig.json
            - ./src:/usr/app/src
            - ./build:/usr/app/build/
        working_dir: /usr/app
        entrypoint: ["sh", "-c", " npm install && npx tsc --watch"]
