services:
    nginx:
        image: nginx
        ports:
            - 8080:80
        volumes:
            ./src/:/usr/share/nginx/html
            ./build/scripts:/usr/share/nginx/html/scripts
    node:
        build: .
        volumes:
            ./src/scripts:/src/
            ./build/scripts:/build/
