services:
    nginx:
        image: nginx
        ports:
            - 8080:80
        volumes:
            - ./build/scripts:/usr/share/nginx/html/scripts
            - ./src:/usr/share/nginx/html
    node:
        build: .
        volumes:
            - ./src:/usr/app/src
            - ./build:/usr/app/build/
